### PR TITLE
Ticket: 229 creating a neutral default theme

### PR DESCRIPTION
**Pull request by JonathanCooperD**

### CODE REVIEW

**Comment by kenwheeler** [comment]
Ok, so this looks good. Before merging though, maybe we can cut the slides down to like 2 or 3 slides, remove all the fluff and imagery and add just a hint of color. Maybe replace that gray with a light blue and have like 2 or 3 example slides with basic "Get Started" type text showcasing headings, text, lists, etc..

**Comment by kenwheeler** [comment]
Without dictating format too much, I would recommend making this the sort of boilerplate you would want to work with if you were starting a new preso. As it stands theres a lot of tear down.

**Comment by JonathanCooperD** [comment]
No problem, I reduced the example to basic slides. Let me know if you want me to make any other changes.

**Comment by JonathanCooperD** [comment]
Sounds good, I'll get some basic elements in place.

**Comment by carlospaelinck** [comment]
Tried this out against the latest Spectacle on `master` and looks solid 👍

**Pull request merged**
