### PR TITLE
Update README.markdown

### LINKED ISSUE #2: How do I download the boilerplate?
How do I download the boilerplate? You probably mean I should clone this repo. But you could also utilize github releases and point visitors there.

### PR DESCRIPTION
**Pull request by morenoh149**
fixes #2

### CODE REVIEW

**Comment by knowbody** [comment]
It can also be downloaded :)

screen shot 2016-01-14 at 17 12 47

**Comment by morenoh149** [comment]
okay

**Comment by knowbody** [comment]
no need to close it @morenoh149, I'll let @kenwheeler decide on that, appreciate your feedback

**Comment by kenwheeler** [comment]
I'll leave it closed for now, going to fix this with a builder archetype when init is ready

**Pull request closed without merging**
