### PR TITLE
eslint some code! (there is no src in this repo)

### PR DESCRIPTION
**Pull request by iamdustan**
^--- :)

### CODE REVIEW

**Comment by knowbody** [comment]
thanks for the PR, could you also fix the linting errors:

```
/../spectacle-boilerplate/presentation/index.js
   3:10   error  "render" is defined but never used  no-unused-vars
   10:3   error  "Code" is defined but never used    no-unused-vars
  172:6   error  Missing semicolon
```

**Comment by iamdustan** [comment]
done!

**Comment by knowbody** [comment]
beautiful, thanks man! @kenwheeler will merge that, I don't have :rocket: rights ;p

**Comment by iamdustan** [comment]
:smile: 

Thanks for *actually* running the linter for me, btw.

**Comment by kenwheeler** [comment]
yall da best

**Pull request merged**
